# Generated by Django 4.0.5 on 2022-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0016_remove_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
