# Generated by Django 4.0.5 on 2022-06-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0017_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='donors',
            field=models.ManyToManyField(blank=True, null=True, related_name='donor', to='tunzapp.donor'),
        ),
    ]
