# Generated by Django 4.0.5 on 2022-06-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0019_remove_child_donors'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='donors',
            field=models.ManyToManyField(blank=True, related_name='child_donor', to='tunzapp.donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunzapp.child'),
        ),
    ]
