# Generated by Django 4.0.5 on 2022-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0021_remove_child_donors'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='donors',
            field=models.ManyToManyField(blank=True, related_name='child_donor', to='tunzapp.donor'),
        ),
    ]
